<nav class="navbar">
                <a href="index.php">
                    <img src="images/logo.png" alt="Logo" class="logo">
                </a>
                <div class="dropdown">
                    <button onclick="myFunction()" class="dropbtn">Select an Option...<span class="arrow">&#709;</span></button>
                    <div id="myDropdown" class="dropdown-content">
                        <a href="index.php">Home</a>
                        <a href="pets.php">Pets</a>
                        <a href="add.php">Add More</a>
                        <a href="gallery.php">Gallery</a>
                        <a href="details.php">Details Page</a>
                    </div>
                </div>

                <div class="search-bar">
                    <input type="text" class="search-input" placeholder="Search">
                </div>
                <i class="material-icons search-icon">search</i>
            </nav>